### PR TITLE
Updating tests

### PR DESCRIPTION
**Pull request by lgraesser**
- [x] create separate `problems.json` and `experiment_specs.json` for `test/`
- [x] add more tests covering more environments
- [x] fix a few bugs that pop up
- [x] fix `NoDisplayException` problem that breaks ssh and thus circle CI. Full ssh to OpenAI Lab restored!
- [x] setup proper test framework; use `conftest.py` for generic test setup override
- [x] unify test assets using modification of original specs, remove source of human error in specs, prevent future fragmentation
- [x] resetup test to source directly from actual unified experiment specs, minus redundant variations
- [x] fix dqn freeze model saving, add memleak warning and TODO to it. remove from test

### CODE REVIEW

**Comment by kengz** [comment]
Test coverage added. See Codacy `Coverage` section, which reflects the test coverage percentage output from the terminal. A badge is also added to README

**Comment by kengz** [comment]
btw Boltzmann underflow error still occurs (on running lunar sarsa exp). rescheduled to later runs

**Comment by kengz** [comment]
btw if this PR is complete, let me know. I'd like to check a few things before we merge.

**Comment by lgraesser** [comment]
Yes, it's complete. I'll add some more tests once I've added some conv agents

**Comment by kengz** [comment]
checking

**Pull request merged**
